# Generated by Django 4.2.7 on 2026-01-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_testing", "0003_add_signature_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="signatureconfig",
            name="signature_field",
            field=models.CharField(
                default="Signature-Data", max_length=100, verbose_name="签名字段名"
            ),
        ),
        migrations.AddField(
            model_name="signatureconfig",
            name="signature_location",
            field=models.CharField(
                choices=[("header", "Header"), ("body", "Body"), ("query", "Query参数")],
                default="header",
                max_length=20,
                verbose_name="签名位置",
            ),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("MD5", "MD5"),
                    ("SHA1", "SHA1"),
                    ("SHA256", "SHA256"),
                    ("HMAC-SHA1", "HMAC-SHA1"),
                    ("HMAC-SHA256", "HMAC-SHA256"),
                ],
                default="MD5",
                max_length=20,
                verbose_name="签名算法",
            ),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_signature_configs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="extra_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="额外签名参数"),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="是否为默认配置"),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="name",
            field=models.CharField(max_length=100, verbose_name="配置名称"),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="secret_key",
            field=models.CharField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=500,
                verbose_name="签名密钥",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="signatureconfig",
            unique_together={("project", "name")},
        ),
        migrations.AlterModelTable(
            name="signatureconfig",
            table="api_signature_configs",
        ),
    ]
