# Generated by Django 4.2 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0004_signatureconfig_signature_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signatureconfig',
            name='algorithm',
            field=models.CharField(
                choices=[
                    ('MD5', 'MD5'),
                    ('SHA1', 'SHA1'),
                    ('SHA256', 'SHA256'),
                    ('HMAC-SHA1', 'HMAC-SHA1'),
                    ('HMAC-SHA256', 'HMAC-SHA256'),
                    ('RSA-SHA256', 'RSA-SHA256'),
                    ('RSA-SHA512', 'RSA-SHA512'),
                    ('SM2', 'SM2'),
                ],
                default='MD5',
                max_length=20,
                verbose_name='签名算法'
            ),
        ),
        migrations.AddField(
            model_name='signatureconfig',
            name='rsa_private_key',
            field=models.TextField(blank=True, verbose_name='RSA私钥'),
        ),
        migrations.AddField(
            model_name='signatureconfig',
            name='rsa_public_key',
            field=models.TextField(blank=True, verbose_name='RSA公钥'),
        ),
        migrations.AddField(
            model_name='signatureconfig',
            name='sm2_private_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='SM2私钥'),
        ),
        migrations.AddField(
            model_name='signatureconfig',
            name='sm2_public_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='SM2公钥'),
        ),
        migrations.AddField(
            model_name='signatureconfig',
            name='sm2_mode',
            field=models.CharField(
                blank=True,
                choices=[('C1C3C2', 'C1C3C2 (旧标准)'), ('C1C2C3', 'C1C2C3 (新标准)')],
                default='C1C2C3',
                max_length=10,
                verbose_name='SM2模式'
            ),
        ),
    ]
