# Generated by Django 4.2 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_add_rsa_sm2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureconfig',
            name='rsa_encrypt_public_key',
            field=models.TextField(blank=True, verbose_name='RSA加密公钥'),
        ),
    ]
