# Generated by Django 4.2.7 on 2026-02-04 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_testing", "0008_add_script_management"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="script",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="script",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="script",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="script",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scripts",
                to="api_testing.apiproject",
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="script_type",
            field=models.CharField(
                choices=[("python", "Python"), ("javascript", "JavaScript")],
                default="python",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="script",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="signatureconfig",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("MD5", "MD5"),
                    ("SHA1", "SHA1"),
                    ("SHA256", "SHA256"),
                    ("HMAC-SHA1", "HMAC-SHA1"),
                    ("HMAC-SHA256", "HMAC-SHA256"),
                    ("RSA-SHA256", "RSA-SHA256"),
                    ("RSA-SHA512", "RSA-SHA512"),
                    ("RSA-MD5", "RSA-MD5"),
                    ("SM2", "SM2"),
                ],
                default="MD5",
                max_length=20,
                verbose_name="签名算法",
            ),
        ),
        migrations.AlterModelTable(
            name="script",
            table=None,
        ),
    ]
