# Generated by Django 4.2.7 on 2026-02-05 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_testing", "0009_add_test_suite_request_features"),
        (
            "api_testing",
            "0009_alter_script_options_alter_script_unique_together_and_more",
        ),
    ]

    operations = []
