# Generated by Django 4.2.7 on 2026-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_testing", "0010_merge_20260205_1048"),
    ]

    operations = [
        migrations.AddField(
            model_name="testsuiterequest",
            name="require_runtime_input",
            field=models.BooleanField(
                default=False, help_text="执行时是否需要用户输入参数", verbose_name="需要运行时输入"
            ),
        ),
        migrations.AddField(
            model_name="testsuiterequest",
            name="runtime_input_config",
            field=models.JSONField(
                default=dict, help_text="运行时输入参数的配置信息", verbose_name="运行时输入配置"
            ),
        ),
    ]
